# -*- coding: utf-8 -*-
"""GA8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iNQY7ugrYwHntw6sgDf8kIQeMLB9kT33
"""

!pip install streamlit 
import streamlit as st

def find_largest(num1, num2, num3):
    # Check which number is the largest
    if num1 >= num2 and num1 >= num3:
        largest = num1
    elif num2 >= num1 and num2 >= num3:
        largest = num2
    else:
        largest = num3
    return largest

st.title("Find the Largest Number")
st.write("Enter three numbers below:")

num1 = st.number_input("Number 1", value=0)
num2 = st.number_input("Number 2", value=0)
num3 = st.number_input("Number 3", value=0)

if st.button("Find Largest"):
    largest = find_largest(num1, num2, num3)
    st.success(f"The largest number is {largest}.")